### ISSUE TITLE
 CSS

### ISSUE THREAD

**Issue by Riley6639** [Riley6639/Prework-study-guide#2]
#user story
As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

## Acceptance Criteria
GIVEN a prework study guide website
WHEN I view the study guide 
THEN I see a dark blue header and footer, and four boxes with a shadow

**Comment by omarigg04** [comment]
This is a great idea to enhance the readability and accessibility of the prework notes for students. Here's the plan to implement this:

Header and Footer:

Apply a dark blue background color (#00008B).
Ensure the text within the header and footer is appropriately styled for readability against the dark blue background (e.g., white text).
Content Boxes:

Create four distinct content boxes within the main section of the webpage.
Apply a shadow effect to each box to give a slight 3D appearance and distinguish them from the background.
Use consistent padding and margin to ensure the boxes are evenly spaced and have a clean layout.
General Layout:

Utilize CSS for styling and ensure the layout is responsive and accessible on different devices.
Ensure all content is easily readable and well-organized within the boxes.
Next Steps:

Create a new branch for this feature.
Implement the dark blue header and footer.
Structure the content into four boxes with shadows.
Test the layout across different devices and screen sizes.
Submit a pull request for review.
